source "https://supermarket.chef.io"

cookbook 'firewall', '~> 1.2.0'
cookbook 'timezone-ii', git: 'https://github.com/L2G/timezone-ii.git'
cookbook 'nginx', '~> 2.7.6'
cookbook 'mysql', '~> 6.0.22'
cookbook 'database', '~> 4.0.6'
cookbook 'mysql2_chef_gem', '~> 1.0.1'
